import { useEffect, useMemo, useState } from "react";
import { createEmployee, deleteEmployee, getEmployees, updateCredentials } from "../services/employeeService";

const blankPerson = { full_name: "", email: "", password: "", phone: "", designation: "Project Manager", department_id: "" };

export default function AdminPeople({ managers = false }) {
  const [people, setPeople] = useState([]); const [query, setQuery] = useState("");
  const [addForm, setAddForm] = useState(null); const [credentials, setCredentials] = useState(null); const [notice, setNotice] = useState("");
  const load = async () => { try { setPeople((await getEmployees()).employees || []); } catch (error) { setNotice(error.response?.data?.message || "Unable to load people."); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => people.filter((person) => (managers ? Number(person.role_id) === 2 : Number(person.role_id) === 3) && `${person.full_name} ${person.email} ${person.department_name || ""}`.toLowerCase().includes(query.toLowerCase())), [people, query, managers]);
  const saveCredentials = async (event) => { event.preventDefault(); try { await updateCredentials(credentials.employee_id, { email: credentials.email, password: credentials.password }); setNotice("Manager credentials updated. Use the new email/password at the next sign-in."); setCredentials(null); load(); } catch (error) { setNotice(error.response?.data?.message || "Unable to update credentials."); } };
  const savePerson = async (event) => { event.preventDefault(); try { await createEmployee({ ...addForm, role_id: managers ? 2 : 3 }); setNotice(`${managers ? "Manager" : "Employee"} added successfully.`); setAddForm(null); load(); } catch (error) { setNotice(error.response?.data?.message || "Unable to add person."); } };
  return <><div className="d-flex justify-content-between align-items-start gap-3 mb-4"><div><h1 className="admin-page-title">{managers ? "Manager Management" : "Employee Management"}</h1><p className="text-white-50 mb-0">{managers ? "Manage manager accounts and credentials." : "Manage employee accounts and organization assignments."}</p></div><button className="btn btn-primary" onClick={() => setAddForm(blankPerson)}><i className="bi bi-plus-lg me-2" />Add {managers ? "manager" : "employee"}</button></div>
    {notice && <div className="alert alert-info alert-dismissible">{notice}<button className="btn-close" onClick={() => setNotice("")} /></div>}
    {addForm && <PersonForm form={addForm} setForm={setAddForm} save={savePerson} cancel={() => setAddForm(null)} title={`Add ${managers ? "manager" : "employee"}`} />}
    {credentials && <form className="admin-panel mb-4" onSubmit={saveCredentials}><div className="d-flex justify-content-between mb-3"><div><h5 className="mb-0">Edit manager credentials</h5><small className="text-white-50">{credentials.full_name}</small></div><button className="btn-close btn-close-white" type="button" onClick={() => setCredentials(null)} /></div><div className="row g-3"><div className="col-md-6"><label className="form-label">Email</label><input required type="email" className="form-control" value={credentials.email} onChange={(event) => setCredentials({ ...credentials, email: event.target.value })} /></div><div className="col-md-6"><label className="form-label">New password <span className="text-white-50">(optional)</span></label><input minLength="8" type="password" className="form-control" value={credentials.password} onChange={(event) => setCredentials({ ...credentials, password: event.target.value })} placeholder="Leave blank to keep current password" /></div><div><button className="btn btn-primary me-2">Save credentials</button><button type="button" className="btn btn-outline-light" onClick={() => setCredentials(null)}>Cancel</button></div></div></form>}
    <div className="admin-panel"><div className="input-group mb-3"><span className="input-group-text"><i className="bi bi-search" /></span><input className="form-control" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search people" /></div><div className="table-responsive"><table className="table table-dark table-hover align-middle mb-0"><thead><tr><th>Name</th><th>Contact</th><th>Designation</th><th>Department</th><th>Role</th><th>Actions</th></tr></thead><tbody>{visible.map((person) => <tr key={person.employee_id}><td><strong>{person.full_name}</strong></td><td>{person.email}<small className="d-block text-white-50">{person.phone || "—"}</small></td><td>{person.designation}</td><td>{person.department_name || "—"}</td><td><span className="badge text-bg-primary">{person.role_name}</span></td><td className="text-nowrap">{managers && <button className="btn btn-sm btn-outline-light me-2" onClick={() => setCredentials({ ...person, password: "" })} title="Edit email and password"><i className="bi bi-key" /></button>}<button className="btn btn-sm btn-outline-danger" onClick={async () => { try { await deleteEmployee(person.employee_id); load(); } catch { setNotice("Unable to delete this person."); } }}><i className="bi bi-trash" /></button></td></tr>)}{!visible.length && <tr><td colSpan="6" className="text-center text-white-50 py-4">No matching people found.</td></tr>}</tbody></table></div></div></>;
}

function PersonForm({ form, setForm, save, cancel, title }) { return <form className="admin-panel mb-4" onSubmit={save}><div className="d-flex justify-content-between mb-3"><h5 className="mb-0">{title}</h5><button className="btn-close btn-close-white" type="button" onClick={cancel} /></div><div className="row g-3"><div className="col-md-6"><input required className="form-control" placeholder="Full name" value={form.full_name} onChange={(event) => setForm({ ...form, full_name: event.target.value })} /></div><div className="col-md-6"><input required type="email" className="form-control" placeholder="Email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></div><div className="col-md-4"><input required minLength="8" type="password" className="form-control" placeholder="Password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></div><div className="col-md-4"><input className="form-control" placeholder="Phone" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></div><div className="col-md-4"><input required className="form-control" placeholder="Designation" value={form.designation} onChange={(event) => setForm({ ...form, designation: event.target.value })} /></div><div className="col-md-6"><input required min="1" type="number" className="form-control" placeholder="Department ID" value={form.department_id} onChange={(event) => setForm({ ...form, department_id: event.target.value })} /></div><div><button className="btn btn-primary me-2">Save</button><button type="button" className="btn btn-outline-light" onClick={cancel}>Cancel</button></div></div></form>; }
