import { useEffect, useMemo, useState } from "react";
import { createEmployee, deleteEmployee, getEmployees, updateCredentials } from "../services/employeeService";
import { getTasks } from "../services/taskService";
import { buildResourcePeople } from "../components/ResourceMap";

const blankPerson = { full_name: "", email: "", password: "", phone: "", designation: "", department_id: "" };
const initials = (name = "") => name.split(" ").map((part) => part[0]).slice(0,2).join("");
export default function AdminPeople({ managers = false }) {
  const [people, setPeople] = useState([]), [tasks, setTasks] = useState([]), [query, setQuery] = useState(""), [department, setDepartment] = useState("All"), [workload, setWorkload] = useState("All"), [focus, setFocus] = useState(null), [addForm, setAddForm] = useState(null), [credentials, setCredentials] = useState(null), [notice, setNotice] = useState("");
  const load = async () => { try { const [peopleData, taskData] = await Promise.all([getEmployees(), getTasks()]); setPeople(peopleData.employees || []); setTasks(taskData.tasks || []); } catch (error) { setNotice(error.response?.data?.message || "Unable to load people."); } };
  useEffect(() => { load(); }, []);
  const resources = useMemo(() => buildResourcePeople(people, tasks), [people, tasks]);
  const base = managers ? people.filter((person) => Number(person.role_id) === 2).map((person) => ({ ...person, state:"balanced", active: tasks.filter((task)=>task.assigned_by===person.full_name && task.status!=="Completed").length, completed:tasks.filter((task)=>task.assigned_by===person.full_name&&task.status==="Completed").length,workload:0,projects:[] })) : resources;
  const departments = ["All", ...new Set(base.map((person) => person.department_name || "Unassigned"))];
  const visible = base.filter((person) => `${person.full_name} ${person.email} ${person.department_name || ""}`.toLowerCase().includes(query.toLowerCase()) && (department === "All" || (person.department_name || "Unassigned") === department) && (workload === "All" || person.state === workload));
  const savePerson = async (event) => { event.preventDefault(); try { await createEmployee({ ...addForm, role_id: managers ? 2 : 3 }); setAddForm(null); setNotice("Resource added to the organization."); load(); } catch (error) { setNotice(error.response?.data?.message || "Unable to add person."); } };
  const saveCredentials = async (event) => { event.preventDefault(); try { await updateCredentials(credentials.employee_id,{email:credentials.email,password:credentials.password});setCredentials(null);setNotice("Credentials updated.");load(); } catch(error){setNotice(error.response?.data?.message||"Unable to update credentials.");} };
  return <div className="people-command"><header className="command-page-head"><div><span>COMMAND / PEOPLE FIELD</span><h1>{managers ? "Leadership resources" : "People grid"}</h1><p>{managers ? "Inspect the managers coordinating organization delivery." : "Search the organization by capacity, department, and operating state."}</p></div><button className="command-action primary" onClick={() => setAddForm(blankPerson)}><i className="bi bi-plus-lg" />ADD RESOURCE</button></header>
    {notice && <div className="alert alert-info mt-3">{notice}<button className="btn-close float-end" onClick={()=>setNotice("")} /></div>}{addForm && <PersonForm form={addForm} setForm={setAddForm} save={savePerson} cancel={()=>setAddForm(null)} />}{credentials && <form className="admin-panel my-3 p-3" onSubmit={saveCredentials}><h5>Access control · {credentials.full_name}</h5><div className="row g-2"><div className="col-md"><input required type="email" className="form-control" value={credentials.email} onChange={e=>setCredentials({...credentials,email:e.target.value})}/></div><div className="col-md"><input minLength="8" type="password" className="form-control" placeholder="New password (optional)" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})}/></div><div className="col-auto"><button className="btn btn-primary">Save</button><button type="button" className="btn btn-link" onClick={()=>setCredentials(null)}>Cancel</button></div></div></form>}
    <section className="people-filter-bar"><label><i className="bi bi-search" /><input placeholder="Search name, email, department" value={query} onChange={(e)=>setQuery(e.target.value)} /></label><select value={department} onChange={(e)=>setDepartment(e.target.value)}>{departments.map((value)=><option key={value}>{value}</option>)}</select>{!managers && <select value={workload} onChange={(e)=>setWorkload(e.target.value)}>{["All","available","balanced","busy","overloaded"].map((value)=><option key={value}>{value === "All" ? "All capacity states" : value}</option>)}</select>}<span>{visible.length} SIGNALS</span></section>
    <div className="people-layout"><section className="people-grid">{visible.map((person,index)=><button style={{"--resource-index":index}} className={`people-resource ${person.state}`} key={person.employee_id} onClick={()=>setFocus(person)}><span className="people-avatar">{initials(person.full_name)}</span><div className="people-identity"><small>{person.department_name||"Unassigned"}</small><strong>{person.full_name}</strong><p>{person.designation||person.role_name}</p></div><div className="people-capacity"><div><small>CAPACITY</small><b>{person.workload}%</b></div><i><span style={{width:`${person.workload}%`}} /></i></div><div className="people-signals"><span><b>{person.active}</b> active</span><span><b>{person.completed}</b> complete</span><span className={person.state}>{person.state}</span></div></button>)}{!visible.length&&<div className="operational-empty"><i className="bi bi-person-dash"/><div><h3>No resources in this signal range</h3><p>Clear a filter or add a person to this department.</p></div></div>}</section>
      {focus && <aside className="focus-view"><button onClick={()=>setFocus(null)}><i className="bi bi-x-lg"/></button><small>RESOURCE CARD / {String(focus.employee_id).padStart(4,"0")}</small><div className="focus-person"><span>{initials(focus.full_name)}</span><h2>{focus.full_name}</h2><p>{focus.designation}</p></div><section><label>PERSON</label><div><span>Role</span><b>{focus.role_name}</b></div><div><span>Department</span><b>{focus.department_name||"Unassigned"}</b></div></section><section><label>CAPACITY</label><div className="focus-load"><i><span style={{width:`${focus.workload}%`}}/></i><b>{focus.workload}%</b></div><div><span>Active work</span><b>{focus.active}</b></div></section><section><label>PROJECTS</label>{focus.projects?.length?focus.projects.map((project)=><p key={project}>{project}</p>):<p>No current project activity.</p>}</section><section><label>PERFORMANCE</label><div><span>Completed work</span><b>{focus.completed}</b></div><div><span>Availability</span><b className={focus.state}>{focus.state}</b></div></section><footer>{managers&&<button onClick={()=>setCredentials({...focus,password:""})}><i className="bi bi-key"/>ACCESS</button>}<button className="danger" onClick={async()=>{try{await deleteEmployee(focus.employee_id);setFocus(null);load()}catch{setNotice("This resource cannot be removed while linked to work.")}}}><i className="bi bi-trash"/>REMOVE</button></footer></aside>}
    </div>
  </div>;
}
function PersonForm({form,setForm,save,cancel}){const set=(key,value)=>setForm({...form,[key]:value});return <form className="admin-panel my-3 p-4" onSubmit={save}><div className="console-label"><span>+</span><div><small>RESOURCE INTAKE</small><h2>Add person</h2></div></div><div className="row g-3"><div className="col-md-6"><input required className="form-control" placeholder="Full name" value={form.full_name} onChange={e=>set("full_name",e.target.value)}/></div><div className="col-md-6"><input required type="email" className="form-control" placeholder="Email" value={form.email} onChange={e=>set("email",e.target.value)}/></div><div className="col-md-4"><input required minLength="8" type="password" className="form-control" placeholder="Initial password" value={form.password} onChange={e=>set("password",e.target.value)}/></div><div className="col-md-4"><input className="form-control" placeholder="Phone" value={form.phone} onChange={e=>set("phone",e.target.value)}/></div><div className="col-md-4"><input required className="form-control" placeholder="Designation" value={form.designation} onChange={e=>set("designation",e.target.value)}/></div><div className="col-md-6"><input required min="1" type="number" className="form-control" placeholder="Department ID" value={form.department_id} onChange={e=>set("department_id",e.target.value)}/></div><div><button className="btn btn-primary me-2">Add resource</button><button type="button" className="btn btn-outline-light" onClick={cancel}>Cancel</button></div></div></form>}
