import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { getEmployees } from "../services/employeeService";
import { getProjects } from "../services/projectService";
import { getTasks } from "../services/taskService";
import ResourceMap, { buildResourcePeople } from "../components/ResourceMap";

export default function AdminDashboardOverview() {
  const [data, setData] = useState({ people: [], projects: [], tasks: [] }); const [selected, setSelected] = useState(null);
  useEffect(() => { Promise.all([getEmployees(), getProjects(), getTasks()]).then(([people, projects, tasks]) => setData({ people: people.employees || [], projects: projects.projects || [], tasks: tasks.tasks || [] })); }, []);
  const resources = useMemo(() => buildResourcePeople(data.people, data.tasks), [data]); const open = data.tasks.filter((task) => task.status !== "Completed"); const overdue = open.filter((task) => task.due_date?.slice(0, 10) < new Date().toISOString().slice(0, 10)); const flow = [...open].sort((a, b) => (a.due_date || "").localeCompare(b.due_date || "")).slice(0, 5);
  return <div className="command-grid-page"><header className="command-page-head"><div><span>ORGANIZATION / LIVE RESOURCE FIELD</span><h1>Resource command grid</h1><p>People, capacity, projects, work, and outcomes—in one operating picture.</p></div><div className="command-actions"><Link to="/admin/employees" className="command-action"><i className="bi bi-person-plus" />Add person</Link><Link to="/admin/projects" className="command-action primary"><i className="bi bi-bezier2" />Create project</Link></div></header>
    <section className="signal-strip"><div><small>RESOURCE SIGNAL</small><strong>{resources.length}</strong><span>people mapped</span></div><div><small>CAPACITY SIGNAL</small><strong>{resources.filter((p) => p.state === "overloaded").length}</strong><span>overloaded</span></div><div><small>DELIVERY SIGNAL</small><strong>{open.length}</strong><span>open tasks</span></div><div className={overdue.length ? "alert-signal" : ""}><small>RISK SIGNAL</small><strong>{overdue.length}</strong><span>past deadline</span></div><div><small>PROJECT SIGNAL</small><strong>{data.projects.filter((p) => p.status === "Active").length}</strong><span>active spaces</span></div></section>
    <section className="grid-module map-module"><div className="module-heading"><div><span className="module-index">01</span><div><small>ORGANIZATION TOPOLOGY</small><h2>Resource map</h2></div></div><div className="state-legend"><span className="available">Available</span><span className="balanced">Balanced</span><span className="busy">Busy</span><span className="overloaded">Overloaded</span></div></div><ResourceMap people={data.people} tasks={data.tasks} selected={selected} onSelect={setSelected} /></section>
    <div className="command-lower-grid"><section className="grid-module"><div className="module-heading"><div><span className="module-index">02</span><div><small>LIVE RELATIONSHIPS</small><h2>Allocation flow</h2></div></div><Link to="/admin/tasks">Open work grid</Link></div><div className="allocation-flow">{flow.map((task, index) => <article key={task.task_id}><span className="flow-sequence">{String(index + 1).padStart(2, "0")}</span><div><small>PERSON</small><strong>{task.assigned_to || "Unassigned"}</strong></div><i /><div><small>PROJECT</small><strong>{task.project_name}</strong></div><i /><div><small>WORK</small><strong>{task.task_title}</strong></div><span className={`flow-priority ${task.priority?.toLowerCase()}`}>{task.priority}</span></article>)}{!flow.length && <div className="operational-empty"><i className="bi bi-diagram-3" /><div><h3>No allocation paths yet</h3><p>Create a project, add its team, then assign the first work object.</p><Link to="/admin/projects">Build first path</Link></div></div>}</div></section>
      <section className="grid-module alert-module"><div className="module-heading"><div><span className="module-index">03</span><div><small>INTERVENTION QUEUE</small><h2>Capacity alerts</h2></div></div></div>{resources.filter((person) => person.state === "overloaded" || person.state === "busy").sort((a,b)=>b.workload-a.workload).slice(0,5).map((person) => <button key={person.employee_id} onClick={() => setSelected(person)} className="capacity-alert"><span className={person.state} /><div><strong>{person.full_name}</strong><small>{person.department_name}</small></div><b>{person.workload}%</b></button>)}{!resources.some((person) => ["busy","overloaded"].includes(person.state)) && <div className="operational-empty compact"><i className="bi bi-check2-circle" /><p>Capacity is currently within operating range.</p></div>}</section></div>
  </div>;
}
