import { useEffect, useMemo, useState } from "react";
import { getTasks, updateTaskStatus } from "../services/taskService";

const badge = (value) => value === "High" ? "danger" : value === "Completed" ? "success" : value === "In Progress" ? "primary" : value === "Low" ? "secondary" : "warning";
export default function EmployeeTasks() {
  const [tasks, setTasks] = useState([]), [loading, setLoading] = useState(true), [query, setQuery] = useState(""), [filter, setFilter] = useState("All"), [sort, setSort] = useState("due_date"), [page, setPage] = useState(1), [selected, setSelected] = useState(null), [notice, setNotice] = useState("");
  const load = async () => { try { setLoading(true); setTasks((await getTasks()).tasks || []); } catch (e) { setNotice(e.response?.data?.message || "Unable to load your tasks."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => tasks.filter(t => (filter === "All" || t.status === filter) && `${t.task_title} ${t.project_name}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === "priority" ? a.priority.localeCompare(b.priority) : new Date(a.due_date) - new Date(b.due_date)), [tasks, query, filter, sort]);
  const pageSize = 6, visible = filtered.slice((page - 1) * pageSize, page * pageSize), total = Math.max(1, Math.ceil(filtered.length / pageSize));
  useEffect(() => setPage(1), [query, filter, sort]);
  const changeStatus = async (task, status) => { try { await updateTaskStatus(task.task_id, status); setTasks(current => current.map(t => t.task_id === task.task_id ? { ...t, status } : t)); setNotice("Task status updated."); } catch (e) { setNotice(e.response?.data?.message || "Unable to update task status."); } };
  return <main className="container py-4"><div className="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><h2 className="mb-1">My Tasks</h2><p className="text-white-50 mb-0">Track and complete work assigned to you.</p></div><div className="d-flex gap-2"><input className="form-control" placeholder="Search tasks" value={query} onChange={e=>setQuery(e.target.value)} /><select className="form-select" value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Pending</option><option>In Progress</option><option>Completed</option></select><select className="form-select" value={sort} onChange={e=>setSort(e.target.value)}><option value="due_date">Due date</option><option value="priority">Priority</option></select></div></div>{notice && <div className="alert alert-info alert-dismissible"><span>{notice}</span><button className="btn-close" onClick={()=>setNotice("")} /></div>}
  <div className="card glass-panel p-2"><div className="table-responsive"><table className="table table-dark table-hover align-middle mb-0"><thead><tr><th>Task</th><th>Project</th><th>Priority</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>{loading ? [...Array(4)].map((_,i)=><tr key={i}><td colSpan="6"><div className="placeholder-glow"><span className="placeholder col-10" /></div></td></tr>) : visible.length ? visible.map(t=><tr key={t.task_id}><td><strong>{t.task_title}</strong><div className="small text-white-50 text-truncate" style={{maxWidth:240}}>{t.description}</div></td><td>{t.project_name}</td><td><span className={`badge text-bg-${badge(t.priority)}`}>{t.priority}</span></td><td>{t.due_date?.slice(0,10) || "—"}</td><td><select aria-label={`Status for ${t.task_title}`} className="form-select form-select-sm" value={t.status} onChange={e=>changeStatus(t,e.target.value)}><option>Pending</option><option>In Progress</option><option>Completed</option></select></td><td><button className="btn btn-sm btn-outline-light" onClick={()=>setSelected(t)}>Details</button></td></tr>) : <tr><td colSpan="6" className="text-center py-5 text-white-50"><i className="bi bi-clipboard-check fs-2 d-block mb-2" />No tasks match your filters.</td></tr>}</tbody></table></div></div><div className="d-flex justify-content-between align-items-center mt-3 small text-white-50"><span>{filtered.length} task{filtered.length===1?"":"s"}</span><div><button className="btn btn-sm btn-outline-light me-2" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {total}</span><button className="btn btn-sm btn-outline-light ms-2" disabled={page===total} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>{selected && <div className="modal d-block" role="dialog"><div className="modal-dialog"><div className="modal-content bg-dark border-secondary"><div className="modal-header"><h5 className="modal-title">{selected.task_title}</h5><button className="btn-close btn-close-white" onClick={()=>setSelected(null)} /></div><div className="modal-body"><p className="text-white-50">{selected.description || "No description provided."}</p><dl className="row mb-0"><dt className="col-4">Project</dt><dd className="col-8">{selected.project_name}</dd><dt className="col-4">Assigned by</dt><dd className="col-8">{selected.assigned_by || "—"}</dd><dt className="col-4">Due</dt><dd className="col-8">{selected.due_date?.slice(0,10) || "—"}</dd></dl></div></div></div></div>}</main>;
}
