import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { getProjects } from "../services/projectService";
import { createTask } from "../services/taskService";
import { getMlHealth, recommendForTask } from "../services/allocationService";
import { motion } from "../lib/motionShim";

const today = new Date().toISOString().slice(0, 10);
const blank = { project_id: "", task_title: "", description: "", priority: "Medium", status: "Pending", assigned_date: today, due_date: "", assigned_to: "" };
export default function SmartAllocation() {
  const [projects, setProjects] = useState([]), [form, setForm] = useState(blank), [recommendations, setRecommendations] = useState([]), [busy, setBusy] = useState(false), [health, setHealth] = useState({ checking: true, available: false });
  useEffect(() => { Promise.allSettled([getProjects(), getMlHealth()]).then(([projectResult, healthResult]) => { if (projectResult.status === "fulfilled") setProjects(projectResult.value.projects || []); else toast.error("Could not load managed projects."); setHealth(healthResult.status === "fulfilled" ? healthResult.value : { available: false, status: "offline" }); }); }, []);
  const set = (key, value) => { setForm((current) => ({ ...current, [key]: value })); if (["project_id","priority","due_date"].includes(key)) setRecommendations([]); };
  const scan = async (event) => { event.preventDefault(); if (!health.available) return toast.error("ML service is offline. Run npm run start:ml from the backend folder."); if (!form.project_id || !form.task_title || !form.due_date) return toast.error("Project, task, and deadline are required."); setBusy(true); try { const data = await recommendForTask(form); setRecommendations(data.recommendations || []); setHealth((current)=>({...current,model_version:data.model_version||current.model_version})); if (!data.recommendations?.length) toast("No available project members found."); } catch (error) { toast.error(error.response?.data?.message || "AI recommendations are temporarily unavailable."); } finally { setBusy(false); } };
  const assign = async (candidate) => { try { await createTask({ ...form, assigned_to: candidate.employee_id }); toast.success(`${form.task_title} assigned to ${candidate.employee_name}`); setForm(blank); setRecommendations([]); } catch (error) { toast.error(error.response?.data?.message || "Could not assign this task."); } };
  return <div className="ai-match-space"><header className="command-page-head"><div><span>INTELLIGENCE / EMPLOYEE–TASK SUITABILITY</span><h1>AI resource match</h1><p>Define the work signal. The model ranks actual project members; you make the allocation decision.</p></div><div className={`model-status ${health.available ? "" : "offline"}`}><i /><span>{health.checking ? "CHECKING MODEL" : health.available ? "MODEL ONLINE" : "MODEL OFFLINE"}<small>{health.available ? `VERSION ${health.model_version || "1.0.0"}` : "RUN NPM RUN START:FULL"}</small></span></div></header>
    <div className="match-console"><form className="match-input" onSubmit={scan}><div className="console-label"><span>01</span><div><small>WORK SIGNAL</small><h2>Describe the allocation</h2></div></div>{!health.checking&&!health.available&&<div className="ml-offline-note"><i className="bi bi-exclamation-triangle"/><div><strong>Prediction service is not running</strong><span>From the backend folder run <code>npm run start:ml</code>, or use <code>npm run start:full</code> when starting both services. Manual assignment still works.</span></div></div>}<label>PROJECT<select required value={form.project_id} onChange={(e) => set("project_id", e.target.value)}><option value="">Choose managed project</option>{projects.map((project) => <option key={project.project_id} value={project.project_id}>{project.project_name}</option>)}</select></label><label>TASK OBJECT<input required placeholder="e.g. Build authentication API" value={form.task_title} onChange={(e) => set("task_title", e.target.value)} /></label><div className="match-fields"><label>PRIORITY<select value={form.priority} onChange={(e) => set("priority", e.target.value)}>{["High","Medium","Low"].map((value) => <option key={value}>{value}</option>)}</select></label><label>DEADLINE<input required type="date" min={form.assigned_date} value={form.due_date} onChange={(e) => set("due_date", e.target.value)} /></label></div><label>CONTEXT<textarea placeholder="Acceptance criteria or delivery context" value={form.description} onChange={(e) => set("description", e.target.value)} /></label><button className="match-scan" disabled={busy||health.checking||!health.available}><i className={`bi ${busy ? "bi-arrow-repeat" : "bi-crosshair2"}`} />{busy ? "ANALYZING RESOURCE FIELD" : "RUN SUITABILITY SCAN"}</button><p>Manual assignment remains available in the Work page if the service is unavailable.</p></form>
      <section className="match-output"><div className="console-label"><span>02</span><div><small>MODEL OUTPUT</small><h2>Best matches</h2></div></div>{recommendations.length ? <div className="match-list">{recommendations.map((candidate, index) => <motion.article initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .08 }} className={index === 0 ? "top-match" : ""} key={candidate.employee_id}><div className="match-rank">{String(index + 1).padStart(2,"0")}</div><div className="match-person"><small>{index === 0 ? "PRIMARY MATCH" : "ALTERNATE"}</small><h3>{candidate.employee_name}</h3><div className="suitability-rail"><i style={{ width: `${candidate.suitability_score}%` }} /></div><strong>{Math.round(candidate.suitability_score)}% suitability</strong></div><div className="match-reasons"><small>WHY THIS MATCH?</small>{candidate.reasons?.map((reason) => <span key={reason}><i className="bi bi-check2" />{reason}</span>)}</div><button onClick={() => assign(candidate)}>ASSIGN<i className="bi bi-arrow-right" /></button></motion.article>)}</div> : <div className="match-empty"><div className="radar"><i /><i /><i /><span className="bi bi-person-bounding-box" /></div><h3>Awaiting work signal</h3><p>Select a project and describe the task. Results are generated by the trained suitability model—not UI scoring.</p></div>}</section>
    </div>
  </div>;
}
