import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { getProjects } from "../services/projectService";
import { autoAssignProject, getAllocations, predictAllRoles } from "../services/allocationService";

export default function SmartAllocation() {
  const [projects, setProjects] = useState([]); const [allocations, setAllocations] = useState([]);
  const [selected, setSelected] = useState(""); const [predictions, setPredictions] = useState([]); const [busy, setBusy] = useState(false);
  const load = async () => { try { const [projectData, allocationData] = await Promise.all([getProjects(), getAllocations()]); setProjects(projectData.projects || []); setAllocations(allocationData.allocations || []); } catch { toast.error("Could not load allocation data."); } };
  useEffect(() => { load(); }, []);
  const runPredictions = async () => { setBusy(true); try { const data = await predictAllRoles(); setPredictions(data.predictions || []); toast.success(`Predicted ${data.predictions?.length || 0} employee roles`); } catch (error) { toast.error(error.response?.data?.message || "Prediction failed."); } finally { setBusy(false); } };
  const assign = async () => { if (!selected) return toast.error("Choose a project first."); setBusy(true); try { const data = await autoAssignProject(selected); setAllocations(data.allocations || []); toast.success(`${data.allocations?.length || 0} people assigned to ${data.project}`); } catch (error) { toast.error(error.response?.data?.message || "Auto-assignment failed."); } finally { setBusy(false); } };
  return <><div className="d-flex align-items-start justify-content-between gap-3 mb-4"><div><h1 className="manager-page-title">Smart Allocation</h1><p className="text-white-50 mb-0">Predict team roles and build a best-fit project team in seconds.</p></div><button className="btn btn-outline-light" onClick={runPredictions} disabled={busy}><i className="bi bi-stars me-2" />{busy ? "Working…" : "Predict all roles"}</button></div>
    <section className="manager-panel mb-4"><div className="row align-items-end g-3"><div className="col-lg-7"><label className="form-label">Project to staff</label><select className="form-select" value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Select a project</option>{projects.map((project) => <option value={project.project_id} key={project.project_id}>{project.project_name} · {project.maximum_team_size || 5} seats</option>)}</select></div><div className="col-lg-3"><div className="small text-white-50 mb-2">Scoring model</div><span className="badge text-bg-primary">Skills 40% · Experience 30% · Availability 20% · Workload 10%</span></div><div className="col-lg-2"><button className="btn btn-primary w-100" onClick={assign} disabled={busy}><i className="bi bi-lightning-charge-fill me-1" />Auto assign</button></div></div></section>
    {predictions.length > 0 && <section className="manager-panel mb-4"><h5 className="mb-3">Latest role predictions</h5><div className="row g-3">{predictions.map((item) => <div className="col-md-6 col-xl-4" key={item.employeeId}><div className="border border-secondary rounded p-3 h-100"><div className="d-flex justify-content-between gap-2"><strong>{item.employeeName}</strong><span className="badge text-bg-success">{item.confidence}%</span></div><div className="text-primary small mt-1">{item.predictedRole}</div><div className="small text-white-50 mt-2">{item.reason}</div><div className="small mt-2">{item.matchingSkills?.join(" · ") || "General technical profile"}</div></div></div>)}</div></section>}
    <section className="manager-panel"><div className="d-flex justify-content-between align-items-center mb-3"><h5 className="mb-0">Recommended team</h5><button className="btn btn-sm btn-outline-light" onClick={load}>Refresh</button></div><div className="table-responsive"><table className="table table-dark table-hover align-middle mb-0"><thead><tr><th>Employee</th><th>Predicted role</th><th>Allocation score</th><th>Why selected</th></tr></thead><tbody>{allocations.map((item) => <tr key={`${item.employee_id || item.employeeId}-${item.project_id || selected}`}><td>{item.full_name || item.employeeName}</td><td><span className="badge text-bg-primary">{item.predicted_role || item.predictedRole}</span></td><td><strong className="text-success">{item.allocation_score || item.score}%</strong></td><td className="text-white-50 small">{item.explanation}</td></tr>)}{!allocations.length && <tr><td colSpan="4" className="text-center text-white-50 py-5">Run Auto assign to generate the team recommendation.</td></tr>}</tbody></table></div></section></>;
}
