import { useEffect, useState } from "react";
import { useAuth } from "../context/AuthContext";
import SidebarAdmin from "../components/SidebarAdmin";
import SidebarManager from "../components/SidebarManager";
import SidebarEmployee from "../components/SidebarEmployee";
import Navbar from "../components/Navbar";
import { getTasks, createTask, updateTask, deleteTask, updateTaskStatus, getProjects, getEmployees } from "../services/taskService";

const blank = { project_id: "", assigned_to: "", task_title: "", description: "", priority: "Medium", status: "Pending", assigned_date: "", due_date: "" };
export default function Tasks() {
  const { user } = useAuth(); const canManage = [1, 2].includes(Number(user?.role));
  const [tasks, setTasks] = useState([]), [projects, setProjects] = useState([]), [employees, setEmployees] = useState([]), [form, setForm] = useState(blank), [editing, setEditing] = useState(null), [notice, setNotice] = useState(""), [remove, setRemove] = useState(null);
  const load = async () => { try { setTasks((await getTasks()).tasks || []); if (canManage) { setProjects((await getProjects()).projects || []); setEmployees((await getEmployees()).employees || []); } } catch (e) { setNotice(e.response?.data?.message || "Unable to load tasks."); } };
  useEffect(() => { load(); }, []);
  const save = async (e) => { e.preventDefault(); try { editing ? await updateTask(editing.task_id, form) : await createTask(form); setNotice(`Task ${editing ? "updated" : "created"} successfully.`); setEditing(null); setForm(blank); load(); } catch (e) { setNotice(e.response?.data?.message || "Unable to save task."); } };
  const edit = (task) => { setEditing(task); setForm({ project_id: task.project_id, assigned_to: task.assigned_to_id, task_title: task.task_title, description: task.description || "", priority: task.priority, status: task.status, assigned_date: task.assigned_date?.slice(0, 10), due_date: task.due_date?.slice(0, 10) }); };
  const status = async (task, value) => { try { await updateTaskStatus(task.task_id, value); load(); } catch (e) { setNotice(e.response?.data?.message || "Unable to update status."); } };
  const Sidebar = Number(user?.role) === 1 ? SidebarAdmin : Number(user?.role) === 2 ? SidebarManager : SidebarEmployee;
  return <div className="d-flex app-shell"><Sidebar /><div className="flex-grow-1"><Navbar /><main className="container py-4"><div className="d-flex justify-content-between align-items-center mb-4"><div><h2 className="mb-1">{canManage ? "Task Management" : "My Tasks"}</h2><p className="text-white-50 mb-0">{canManage ? "Assign, track, and update delivery work." : "Keep your assigned work moving."}</p></div>{canManage && <button className="btn btn-primary" onClick={() => { setEditing({}); setForm(blank); }}> <i className="bi bi-plus-lg me-1" />Assign Task</button>}</div>{notice && <div className="alert alert-info alert-dismissible"><span>{notice}</span><button className="btn-close" onClick={() => setNotice("")} /></div>}
  {canManage && editing && <div className="card glass-panel p-4 mb-4"><form onSubmit={save} className="row g-3"><h5>{editing.task_id ? "Edit Task" : "Assign Task"}</h5><div className="col-md-6"><select required className="form-select" value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">Select project</option>{projects.map(p=><option key={p.project_id} value={p.project_id}>{p.project_name}</option>)}</select></div><div className="col-md-6"><select required className="form-select" value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}><option value="">Assign employee</option>{employees.map(e=><option key={e.employee_id} value={e.employee_id}>{e.full_name}</option>)}</select></div><div className="col-md-6"><input required className="form-control" placeholder="Task title" value={form.task_title} onChange={e=>setForm({...form,task_title:e.target.value})}/></div><div className="col-md-3"><select className="form-select" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{["High","Medium","Low"].map(x=><option key={x}>{x}</option>)}</select></div><div className="col-md-3"><select className="form-select" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{["Pending","In Progress","Completed"].map(x=><option key={x}>{x}</option>)}</select></div><div className="col-md-6"><input required type="date" className="form-control" value={form.assigned_date} onChange={e=>setForm({...form,assigned_date:e.target.value})}/></div><div className="col-md-6"><input required type="date" className="form-control" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></div><div className="col-12"><textarea className="form-control" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div><button className="btn btn-success me-2">Save Task</button><button type="button" className="btn btn-outline-light" onClick={()=>setEditing(null)}>Cancel</button></div></form></div>}
  <div className="card glass-panel p-3 table-responsive"><table className="table table-dark table-hover align-middle mb-0"><thead><tr><th>Task</th><th>Project</th><th>Assignee</th><th>Priority</th><th>Due</th><th>Status</th>{canManage && <th>Actions</th>}</tr></thead><tbody>{tasks.length ? (tasks.map((t) => (<tr key={t.task_id}><td><strong>{t.task_title}</strong><div className="small text-white-50">{t.description}</div></td><td>{t.project_name}</td><td>{t.assigned_to}</td><td><span className="badge text-bg-secondary">{t.priority}</span></td><td>{t.due_date?.slice(0, 10)}</td><td>{Number(user?.role) === 3 ? <select className="form-select form-select-sm" value={t.status} onChange={(e) => status(t, e.target.value)}>{["Pending", "In Progress", "Completed"].map((x) => <option key={x}>{x}</option>)}</select> : <span className="badge text-bg-primary">{t.status}</span>}</td>{canManage && <td><button className="btn btn-sm btn-outline-warning me-2" onClick={() => edit(t)}>Edit</button><button className="btn btn-sm btn-outline-danger" onClick={() => setRemove(t)}>Delete</button></td>}</tr>))) : (<tr><td colSpan={canManage ? 7 : 6} className="text-center py-4 text-white-50">No tasks found.</td></tr>)}</tbody></table></div>
  {remove&&<div className="modal d-block" tabIndex="-1"><div className="modal-dialog"><div className="modal-content bg-dark"><div className="modal-body"><h5>Delete task?</h5><p>This action cannot be undone.</p><button className="btn btn-danger me-2" onClick={async()=>{try{await deleteTask(remove.task_id);setRemove(null);load();}catch(e){setNotice("Unable to delete task.");}}}>Delete</button><button className="btn btn-secondary" onClick={()=>setRemove(null)}>Cancel</button></div></div></div></div>}</main></div></div>;
}
